name: flutter_neat_and_clean_calendar
description: >-
  Simple and clean flutter calendar with ability to  slide up/down to show
  weekly/monthly calendar.  Fork of
  https://pub.dev/packages/flutter_clean_calendar
version: 0.4.15
homepage: https://github.com/rwbr/flutter_neat_and_clean_calendar

environment:
  sdk: ^3.6.0

dependencies:
  change_app_package_name: ^1.4.0
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^7.0.0
  intl: ^0.19.0
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

platforms:
  ios:
  android:
  web:
  macos:
